"""rich text post

Revision ID: 60a203e7a942
Revises: 4beda5e94f81
Create Date: 2016-08-19 16:53:00.187647

"""

# revision identifiers, used by Alembic.
revision = '60a203e7a942'
down_revision = '4beda5e94f81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
